server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: review_web
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml